#ifndef _REND_H
#define _REND_H

#include <light.h>

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

Light_Module_Declare(rend);

#define REND_BLACK      (uint16_t)0x0000
#define REND_WHITE      (uint16_t)0xFFFF

// glyphs[] is indexed directly by ASCII character code; unrendered code points are NULL.
// every non-NULL entry points to a (char_width+7)/8 * char_height byte buffer: 1 bit per
// pixel, MSB-first, row-major, 1 = black and 0 = white. this layout is shared with the C
// source/header pairs generated by font-crusher's 'crush render new' command, which emit
// glyph tables of exactly this shape wrapped in an extern const rend_font_t instance
#define REND_FONT_GLYPH_TABLE_SIZE 128

#define REND_POINT_1    1
#define REND_POINT_2    2
#define REND_POINT_3    3
#define REND_POINT_4    4
#define REND_POINT_5    5
#define REND_POINT_6    6
#define REND_POINT_7    7
#define REND_POINT_8    8

typedef struct rend_font {
    const uint8_t *const *glyphs;
    uint8_t char_width;
    uint8_t char_height;
} rend_font_t;

typedef struct rend_context {
    const uint8_t *name;
    uint8_t *buffer;
    size_t buffer_length;
    uint16_t dim_x;
    uint16_t dim_y;
    uint8_t px_bits;
    uint8_t px_bytes;
    uint8_t point_radius;
    uint16_t color_fg;
    uint16_t color_bg;
    const rend_font_t *font;
} rend_context_t;

typedef struct rend_point2d {
    uint16_t x;
    uint16_t y;
} rend_point2d;

rend_context_t *rend_context_create(const uint8_t *name, uint16_t width, uint16_t height, uint8_t px_bits);
void rend_context_set_font(rend_context_t *ctx, const rend_font_t *font);

void rend_draw_circle(const rend_context_t *ctx, rend_point2d centre, uint16_t radius, bool fill);
void rend_draw_point(const rend_context_t *img, rend_point2d p);
void rend_draw_line(const rend_context_t *ctx, rend_point2d p0, rend_point2d p1, bool solid);
void rend_draw_clear(const rend_context_t *ctx);
void rend_draw_text(const rend_context_t *ctx,
                    rend_point2d p, const uint8_t *text);
void rend_draw_rect(const rend_context_t *ctx,
                    rend_point2d p0, rend_point2d p1, bool fill);

uint8_t *rend_print_buffer(const rend_context_t *ctx);
void rend_debug_buffer_print_stdout(const rend_context_t *ctx);

#endif