#ifndef _REND_H
#define _REND_H

#include <light.h>

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

Light_Module_Declare(rend);

#define REND_BLACK      (uint16_t)0x0000
#define REND_WHITE      (uint16_t)0xFFFF

// glyphs[] is indexed directly by ASCII character code; unrendered code points are NULL.
// every non-NULL entry points to a (char_width+7)/8 * char_height byte buffer: 1 bit per
// pixel, MSB-first, row-major, 1 = black and 0 = white. this layout is shared with the C
// source/header pairs generated by font-crusher's 'crush render new' command, which emit
// glyph tables of exactly this shape wrapped in an extern const rend_font_t instance
#define REND_FONT_GLYPH_TABLE_SIZE 128

#define REND_POINT_1    1
#define REND_POINT_2    2
#define REND_POINT_3    3
#define REND_POINT_4    4
#define REND_POINT_5    5
#define REND_POINT_6    6
#define REND_POINT_7    7
#define REND_POINT_8    8

// rotation applies only to how logical (dim_x, dim_y) coordinates map onto the
// underlying physical buffer -- the buffer itself is always allocated at creation-time
// dimensions, matching whatever the display driver expects. REND_ROTATE_90/270 swap
// dim_x/dim_y so callers can keep drawing in whatever orientation is natural for their
// content (e.g. wide text) regardless of how the panel is physically mounted
#define REND_ROTATE_0     0
#define REND_ROTATE_90    1
#define REND_ROTATE_180   2
#define REND_ROTATE_270   3

// mirrors the logical coordinate space before rotation is applied (see
// rend_context_set_flip()). REND_FLIP_BOTH is equivalent to REND_ROTATE_180 applied on
// its own, but composes independently with whatever rotation is also set
#define REND_FLIP_NONE          0
#define REND_FLIP_HORIZONTAL    1
#define REND_FLIP_VERTICAL      2
#define REND_FLIP_BOTH          3

typedef struct rend_font {
    const uint8_t *const *glyphs;
    uint8_t char_width;
    uint8_t char_height;
} rend_font_t;

// 2x3 affine transform (the bottom row of the equivalent 3x3 homogeneous matrix is
// always [0 0 1], so it isn't stored):
//   phys_x = a*x + b*y + tx
//   phys_y = c*x + d*y + ty
// every logical-to-physical coordinate mapping (currently just rotation) is expressed
// as one of these, computed once when set rather than re-derived per pixel
typedef struct rend_transform {
    int32_t a, b, tx;
    int32_t c, d, ty;
} rend_transform_t;

typedef struct rend_context {
    const uint8_t *name;
    uint8_t *buffer;
    // NULL unless rend_context_enable_double_buffer() has been called -- the other half
    // of the front/back pair swapped by rend_context_swap_buffers()
    uint8_t *buffer_back;
    size_t buffer_length;
    // dim_x/dim_y are the LOGICAL dimensions callers draw against -- for
    // REND_ROTATE_90/270 these are swapped relative to phys_dim_x/phys_dim_y, which
    // describe the buffer's actual fixed layout (set once at creation and never
    // changed by rotation)
    uint16_t dim_x;
    uint16_t dim_y;
    uint16_t phys_dim_x;
    uint16_t phys_dim_y;
    uint8_t rotation;
    uint8_t flip;
    rend_transform_t transform;
    uint8_t px_bits;
    uint8_t px_bytes;
    uint8_t point_radius;
    uint16_t color_fg;
    uint16_t color_bg;
    const rend_font_t *font;
} rend_context_t;

typedef struct rend_point2d {
    uint16_t x;
    uint16_t y;
} rend_point2d;

rend_context_t *rend_context_create(const uint8_t *name, uint16_t width, uint16_t height, uint8_t px_bits);
void rend_context_set_font(rend_context_t *ctx, const rend_font_t *font);
// sets how logical (dim_x, dim_y) coordinates map onto the physical buffer allocated at
// creation time (see REND_ROTATE_* above). updates ctx->dim_x/dim_y in place; existing
// buffer content is not transformed, so this is meant to be called once during setup,
// before any drawing
void rend_context_set_rotation(rend_context_t *ctx, uint8_t rotation);
// mirrors the logical coordinate space (see REND_FLIP_* above), composing with whatever
// rotation is also set -- order doesn't matter, call this and rend_context_set_rotation()
// in either order. like rotation, existing buffer content is not transformed, so this
// is meant to be called once during setup, before any drawing
void rend_context_set_flip(rend_context_t *ctx, uint8_t flip);
// allocates a second buffer_length-sized buffer alongside ctx->buffer, for callers who
// want to render the next frame while a previous one is still being flushed to a display
// (see rend_context_swap_buffers()). optional -- most callers don't need this
void rend_context_enable_double_buffer(rend_context_t *ctx);
// flips ctx->buffer to the other allocated buffer (front/back swap). returns false
// (no-op) if double-buffering hasn't been enabled -- there's nothing to swap to. callers
// driving an async display update from this context should confirm nothing is still
// reading the target buffer first (see light_display_render_context_busy())
bool rend_context_swap_buffers(rend_context_t *ctx);
// maps a LOGICAL axis-aligned rect onto the PHYSICAL buffer's coordinate space, writing
// the result back as a normalised inclusive (min, max) pair. rotation and flip reorder
// which logical corner lands at which physical extreme, so the corners are transformed
// and then min/max'd rather than assumed to stay in order. every transform this supports
// maps axis-aligned rects to axis-aligned rects, so transforming two opposite corners
// recovers the exact physical bounds -- there's no need to visit all four. added for
// display drivers doing partial-region updates, which address the physical buffer while
// their callers naturally think in logical coordinates
void rend_transform_rect(const rend_context_t *ctx, rend_point2d p0, rend_point2d p1,
                         rend_point2d *out_min, rend_point2d *out_max);
// the inverse of the above, for a single point: maps a PHYSICAL buffer coordinate back into
// the LOGICAL space callers draw in. added for input rather than output -- a touch panel
// reports in the display's own physical frame, while everything layered above rend thinks
// in logical coordinates, and under rotation those are not the same point.
//
// exact, with no rounding: every rotation and flip matrix has entries in {-1, 0, 1} and
// determinant +/-1, and composing them preserves that, so the inverse is integer arithmetic
// (and 1/det == det). the result is clamped into dim_x/dim_y, since a touch panel whose
// coordinate range is slightly larger than the display's can otherwise map outside it
rend_point2d rend_untransform_point(const rend_context_t *ctx, rend_point2d phys);

// 1.0 in the Q15 fixed-point scale rend_blit_rotated() takes
#define REND_SCALE_ONE  32768

// samples `src` into ctx's own buffer, rotated by `angle_deg` about the buffer centre and
// scaled by `scale_q15` (REND_SCALE_ONE == 1:1). `src` must be a buffer of exactly ctx's
// geometry and pixel format -- typically the context's own back buffer, holding a previously
// rendered frame.
//
// works in PHYSICAL buffer space and ignores ctx->transform entirely: this rotates an image,
// it does not draw through the logical-to-physical mapping. that is what makes it usable for
// animating between two rotations, where the transform is precisely the thing in flux.
//
// INVERSE sampled -- for every destination pixel it maps back into the source and takes the
// nearest pixel. mapping source pixels forward instead would scatter them and leave unwritten
// gaps that widen with the scale factor. destination pixels whose source falls outside the
// buffer are left as they are, so clear first if that matters.
//
// SCALE IS NOT DECORATION: a w*h image rotated by 45 degrees needs a box of
// w*|sin| + h*|cos| on a side, so at 1:1 the corners fall outside a fixed buffer and are cut
// off part-way through a turn. pass rend_scale_inscribed() to keep the whole image visible.
//
// 16bpp only for now; a 1bpp path can follow if a mono panel ever needs one
void rend_blit_rotated(const rend_context_t *ctx, const uint8_t *src,
                       int16_t angle_deg, int32_t scale_q15);
// the largest scale at which a rotation by `angle_deg` still fits entirely inside a
// buffer of ctx's dimensions -- REND_SCALE_ONE at 0/180 degrees, smallest at 45
int32_t rend_scale_inscribed(const rend_context_t *ctx, int16_t angle_deg);

void rend_draw_circle(const rend_context_t *ctx, rend_point2d centre, uint16_t radius, bool fill);
// draws the part of a circle between two angles.
//
// ANGLE CONVENTION: 0 degrees points RIGHT (+x), and angles increase CLOCKWISE as seen on
// screen -- so 90 is straight DOWN. that follows from rend's y growing downward, and is
// stated explicitly because the opposite convention is equally defensible in the abstract
// and this is the first thing anyone gets wrong. angles outside 0..360 are wrapped, and
// end < start sweeps the long way round rather than drawing nothing.
//
// the step is derived from the radius so the arc never has gaps (see the implementation);
// the cost is that a pixel may be written twice where two steps land in the same cell, which
// is cheaper than de-duplicating and harmless for every drawing operation rend has
void rend_draw_arc(const rend_context_t *ctx, rend_point2d centre, uint16_t radius,
                   int16_t start_deg, int16_t end_deg);
// a rectangle with rounded corners: the four straight edges shortened by the radius, plus a
// quarter arc at each inset corner. the radius is clamped to half the shorter side, so an
// over-large one degenerates into a stadium rather than drawing nonsense
void rend_draw_rect_rounded(const rend_context_t *ctx, rend_point2d p0, rend_point2d p1,
                            uint16_t radius, bool fill);
void rend_draw_point(const rend_context_t *img, rend_point2d p);
void rend_draw_line(const rend_context_t *ctx, rend_point2d p0, rend_point2d p1, bool solid);
void rend_draw_clear(const rend_context_t *ctx);
void rend_draw_text(const rend_context_t *ctx,
                    rend_point2d p, const uint8_t *text);
void rend_draw_rect(const rend_context_t *ctx,
                    rend_point2d p0, rend_point2d p1, bool fill);

uint8_t *rend_print_buffer(const rend_context_t *ctx);
void rend_debug_buffer_print_stdout(const rend_context_t *ctx);

#endif